
#Lab 8.1 Numpy 1D trong Python

Thời lượng ước tính: **30** phút

## Mục tiêu

Sau khi hoàn thành lab này, bạn sẽ có thể:

-   Nhập và sử dụng thư viện `numpy`
-   Thực hiện các thao tác với `numpy`


<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="pre">Chuẩn bị</a></li>
        <li>
            <a href="numpy">Numpy là gì?</a>
            <ul>
                <li><a href="type">Kiểu (Type)</a></li>
                <li><a href="val">Gán giá trị</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="list">Gán giá trị với List</a></li>
                <li><a href="other">Các thuộc tính khác</a></li>
            </ul>
        </li>
        <li>
            <a href="op">Các hoạt động mảng Numpy</a>
            <ul>
                <li><a href="add">Cộng mảng</a></li>
                <li><a href="multi">Nhân mảng</a></li>
                <li><a href="prod">Tích của 2 mảng Numpy</a></li>
                <li><a href="dot">Tích vô hướng</a></li>
                <li><a href="cons">Cộng hằng số vào mảng Numpy</a></li>
            </ul>
        </li>
        <li><a href="math">Hàm số</a></li>
        <li><a href="lin">Linspace</a></li>
    </ul>

</div>

<hr>


<h2 id="pre">Chuẩn bị</h2>


In [1]:
# Import the libraries

import time
import sys
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
# Plotting functions

def Plotvec1(u, z, v):

    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')

    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

Tạo một list Python như sau:

In [3]:
# Create a python list

a = ["0", 1, "two", "3", 4]

Chúng ta có thể truy cập dữ liệu thông qua chỉ mục:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneList.png" width="660" />


Chúng ta có thể truy cập từng phần tử bằng dấu ngoặc vuông như sau:

In [4]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


<hr>


<h2 id="numpy">Numpy là gì?</h2>



Mảng numpy tương tự như list. Nó thường cố định về kích thước và mỗi phần tử là cùng kiểu. Chúng ta có thể truyền một list vào mảng numpy bằng cách nhập numpy đầu tiên:

In [5]:
# import numpy library

import numpy as np

Sau đó, chúng ta ép kiểu list như sau:

In [6]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Mỗi phần tử có cùng kiểu, trong trường hợp này là các số nguyên:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500" />


Như với list, chúng ta có thể truy cập từng phần tử thông qua dấu ngoặc vuông:

In [7]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


<h3 id="type">Kiểu</h3>


Nếu kiểm tra kiểu của mảng, ta được <b>numpy.ndarray</b>:

In [8]:
# Check the type of the array

type(a)

numpy.ndarray

Vì các mảng không chứa dữ liệu cùng kiểu, chúng ta có thể sử dụng thuộc tính "dtype" để lấy Kiểu dữ liệu của các phần tử của mảng. Trong trường hợp này là số nguyên 64 bit:

In [9]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

Chúng ta có thể tạo một mảng numpy với các số thực:

In [10]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

Khi kiểm tra kiểu của mảng, ta được <b>numpy.ndarray</b>:

In [11]:
# Check the type of array

type(b)

numpy.ndarray

Nếu kiểm tra thuộc tính <code> dtype</code>, chúng ta sẽ thấy float64 vì các phần tử không phải là số nguyên:

In [12]:
# Check the value type

b.dtype

dtype('float64')

<h3 id="val">Gán giá trị</h3>


Chúng ta có thể thay đổi giá trị của mảng, hãy xem xét mảng <code> c</code>:

In [13]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

Chúng ta có thể thay đổi phần tử đầu tiên của mảng thành 100 như sau:

In [14]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

Chúng ta có thể thay đổi phần tử thứ 5 của mảng thành 0 như sau:

In [15]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

<h3 id="slice">Slicing</h3>


Giống list, chúng ta có thể cắt mảng numpy, chọn các phần tử từ 1 đến 3 và gán nó vào mảng numpy <code> d</code> mới như sau:

In [16]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

Chúng ta có thể gán các chỉ mục tương ứng cho các giá trị mới như sau:

In [17]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

<h3 id="list">Gán giá trị với List</h3>


Tương tự, chúng ta có thể sử dụng một list để chọn một chỉ mục cụ thể.
List 'select' chứa một số giá trị:

In [20]:
# Create the index list

select = [0, 2, 3]

Chúng ta có thể sử dụng list như một đối số trong ngoặc. Đầu ra là các phần tử tương ứng với chỉ số cụ thể:

In [21]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

Chúng ta có thể gán các phần tử được chỉ định cho một giá trị mới. Ví dụ, chúng ta có thể gán các giá trị cho 100 000 như sau:

In [22]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

<h3 id="other">Các thuộc tính khác</h3>


Hãy xem lại một số thuộc tính cơ bản của mảng bằng cách sử dụng mảng <code> a</code>:

In [23]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Thuộc tính <code> size</code> là số phần tử trong mảng:

In [24]:
# Get the size of numpy array

a.size

5

Hai thuộc tính tiếp theo sẽ có ý nghĩa hơn khi chúng ta được kích thước cao hơn nhưng hãy xem lại chúng. Thuộc tính <code> ndim</code> đại diện cho số lượng chiều hoặc thứ hạng của mảng, trong trường hợp này là:

In [25]:
# Get the number of dimensions of numpy array

a.ndim

1

Thuộc tính <code> shape</code> là một tập hợp các số nguyên cho biết kích thước của mảng theo từng chiều:

In [26]:
# Get the shape/size of numpy array

a.shape

(5,)

In [27]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [28]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [29]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [30]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [31]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [32]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

<hr>


<h2 id="op">Hoạt động mảng Numpy</h2>


<h3 id="add">Cộng mảng</h3>


Xem xét mảng numpy <code> u</code>:

In [33]:
u = np.array([1, 0])
u

array([1, 0])

Xem xét mảng numpy <code>v</code>:


In [34]:
v = np.array([0, 1])
v

array([0, 1])

Chúng ta có thể cộng hai mảng và gán nó cho z:

In [35]:
# Numpy Array Addition

z = u + v
z

array([1, 1])

Phép toán tương đương với phép cộng vectơ:

In [37]:
# Plot numpy arrays

Plotvec1(u, z, v)

NameError: name 'plotvec1' is not defined

<h3 id="multi">Nhân mảng</h3>


Hãy xem xét mảng numpy vectơ <code> y</code>:

In [38]:
# Create a numpy array

y = np.array([1, 2])
y

array([1, 2])

Chúng ta có thể nhân mọi phần tử trong mảng với 2:

In [39]:
# Numpy Array Multiplication

z = 2 * y
z

array([2, 4])

Điều này tương đương với việc nhân một vectơ với một đại lượng vô hướng:

<h3 id="prod">Tích của 2 mảng numpy</h3>


Hãy xem xét mảng <code> u</code> sau:

In [40]:
# Create a numpy array

u = np.array([1, 2])
u

array([1, 2])

Hãy xem xét mảng sau <code> v</code>:

In [41]:
# Create a numpy array

v = np.array([3, 2])
v

array([3, 2])

Tích của hai mảng numpy <code> u</code> và <code> v</code> được cho bởi:

In [42]:
# Calculate the production of two numpy arrays

z = u * v
z

array([3, 4])

<h3 id="dot">Tích vô hướng</h3>


Tích vô hướng của hai mảng numpy <code> u</code> và <code> v</code> được cho bởi:

In [43]:
# Calculate the dot product

np.dot(u, v)

7

<h3 id="cons">Cộng hằng số vào một mảng Numpy</h3>


Hãy xem xét mảng sau:

In [44]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1])
u

array([ 1,  2,  3, -1])

Cộng hằng số 1 vào mỗi phần tử trong mảng:

In [45]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

Quá trình này được tóm tắt trong hình động sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneAdd.gif" width="500" />


<hr>


<h2 id="math">Hàm số</h2>


Chúng ta có thể truy cập giá trị của <code> pi</code> trong numpy như sau:

In [46]:
# The value of pi

np.pi

3.141592653589793

Chúng ta có thể tạo mảng numpy sau trong Radian:

In [47]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])

Chúng ta có thể vận dụng hàm <code> sin</code> cho mảng <code> x</code> và gán các giá trị cho mảng <code> y</code>; điều này áp dụng hàm sin cho mỗi phần tử trong mảng:

In [48]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

<hr>


<h2 id="lin">Linspace</h2>


<code> Linspace</code> là một hàm hữu ích để vẽ các hàm toán học. Linspace trả về các số cách đều nhau trong một khoảng được chỉ định. Chúng ta chỉ định điểm bắt đầu và kết thúc của dãy. Tham số "num" cho biết số lượng mẫu cần tạo, trong trường hợp này là 5:

In [49]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

Nếu thay đổi tham số <code> num</code> thành 9, chúng ta được 9 số cách đều nhau trong khoảng từ -2 đến 2:

In [50]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

Chúng ta có thể sử dụng hàm <code> linspace</code> để tạo 100 mẫu cách đều nhau từ khoảng 0 đến 2π:

In [52]:
# Makeup a numpy array within [0, 2π] and 100 elements

x = np.linspace(0, 2*np.pi, num=100)

Chúng ta có thể vận dụng hàm sin cho từng phần tử trong mảng <code> x</code> và gán nó cho mảng <code> y</code>:

In [53]:
# Calculate the sine of x list

y = np.sin(x)

In [54]:
# Plot the result

plt.plot(x, y)

NameError: name 'plt' is not defined

<hr>


<h2 id="quiz">Quiz về Mảng Numpy 1D</h2>


Thực hiện phép trừ vectơ sau trong numpy: u-v

In [57]:
# Write your code below and press Shift+Enter to execute

u = np.array([1, 0])
v = np.array([0, 1])
print(u-v)

[ 1 -1]


<details><summary>Bấm vào đây để xem đáp án</summary>

```python
u - v
```

</details>


<hr>


Nhân mảng numpy z với -2:

In [58]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])
print(z*-2)

[-4 -8]


<details><summary>Bấm vào đây để xem đáp án</summary>

```python
-2 * z
```

</details>


<hr>


Xem xét list <code> [1, 2, 3, 4, 5]</code> và <code> [1, 0, 1, 0, 1]</code>, sau đó truyền cả hai danh sách sang một mảng numpy rồi nhân chúng với nhau:

In [60]:
# Write your code below and press Shift+Enter to execute
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])
x*y

array([1, 0, 3, 0, 5])

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b
```

</details>


<hr>


Chuyển đổi list <code> [-1, 1]</code> và <code> [1, 1]</code> thành mảng numpy <code> a</code> và <code> b</code>. Sau đó, vẽ các mảng dưới dạng vectơ bằng cách sử dụng hàm <code> Plotvec2</code> và tìm tích vô hướng:

In [63]:
# Write your code below and press Shift+Enter to execute
a = np.array([-1,1])
b = np.array([1,1])
Plotvec2(a,b)
print(np.plot(a,b))


NameError: name 'plt' is not defined

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
a = np.array([-1, 1])
b = np.array([1, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a,b))

```

</details>


<hr>


Chuyển đổi list <code> [1, 0]</code> và <code> [0, 1]</code> thành mảng numpy <code> a</code> và <code> b</code>. Sau đó, vẽ các mảng dưới dạng vectơ bằng cách sử dụng hàm <code> Plotvec2</code> và tìm tích vô hướng:

In [64]:
# Write your code below and press Shift+Enter to execute
a = np.array([1,0])
b = np.array([0,1])
Plotvec2(a,b)
print(np.plot(a,b))

NameError: name 'plt' is not defined

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
a = np.array([1, 0])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))

```

</details>


<hr>


Chuyển đổi list <code> [1, 1]</code> và <code> [0, 1]</code> thành mảng numpy <code> a</code> và <code> b</code>. Sau đó, vẽ các mảng dưới dạng vectơ bằng cách sử dụng hàm <code> Plotvec2</code> và tìm tích vô hướng:

In [ ]:
# Write your code below and press Shift+Enter to execute
a = np.array([1,1])
b = np.array([0,1])
Plotvec2(a,b)
print(np.plot(a,b))

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
a = np.array([1, 1])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))
print("The dot product is", np.dot(a, b))

```

</details>



<hr>


Tại sao kết quả tích vô hướng của <code> [-1, 1]</code> và <code> [1, 1]</code> và tích vô hướng của <code> [1, 0] </code> và <code> [0, 1]</code> bằng 0, nhưng không bằng 0 đối với tích vô hướng của <code> [1, 1]</code> và <code> [0, 1]</code> ? <p><i> Gợi ý: Nghiên cứu các số liệu tương ứng, chú ý đến hướng mũi tên trỏ đến. </i></p>

In [ ]:
# Write your code below and press Shift+Enter to execute
Vì với tích vô hướng của [-1,1] và [1,1] thì hướng của mũi tên Vector [-1, 1] trỏ về hướng đường chéo phải trên, trong khi vector [1, 1] trỏ về hướng đường chéo trái dưới và vì có 1 vector có 1 phần tử có dấu âm nên khi tính tích thì dẫn tới nửa cộng nửa trừ nên triệt tiêu giá trị
Với tích vô hướng của [1,0] và [0,1] thì hướng của mũi tên vuông góc với nhau nên tích sẽ bằng 0
Với tích vô hướng của [1,1] và [0,1] thì hướng của mũi tên Vector [1, 1] trỏ về phía hướng đường chéo trái dưới, trong khi vector [0, 1] trỏ về phía hướng đứng lên và khi nhân tích vô hướng thì 1 nửa sẽ bằng 0 còn nửa còn lại bằng 1 nên tổng sẽ là 1

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero.

```

</details>



<hr>
Nguồn: IBM
<hr>
