In [24]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [12]:
# Your code here
import numpy as np
matran1 = np.random.randint(1,11,size=[3,3])
matran2 = np.random.randint(1,11,size=[3,3])
print ('Ma trận 1 là: ', matran1) #Đăt đây để k dính for sẽ bị lặp lại
print ('Ma trận 2 là: ', matran2)


Ma trận 1 là:  [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]
Ma trận 2 là:  [[5 4 8]
 [8 3 6]
 [5 2 8]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [17]:
# Your code here
print('cộng 2 ma trận: ', matran1+matran2)
print('Nhân 2 ma trận: ', matran1*matran2)
print('Tích vô hướng của 2 ma trận: ', np.dot(matran1,matran2))

cộng 2 ma trận:  [[12  8 16]
 [13 10 16]
 [ 8  9 16]]
Nhân 2 ma trận:  [[35 16 64]
 [40 21 60]
 [15 14 64]]
Tích vô hướng của 2 ma trận:  [[107  56 144]
 [131  61 162]
 [111  49 130]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [42]:
# Your code here:

k = np.array([[2,6,9], [6,1,4]])
tong = np.sum(k)
print(f"Tổng của 1 mảng numpy {k} là {tong}")

Tổng của 1 mảng numpy [[2 6 9]
 [6 1 4]] là 28
