In [8]:
pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/75/5b/ca6c8bd14007e5ca171c7c03102d17b4f4e0ceb53957e8c44343a9546dcc/numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 1.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 26.7 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [3]:

# Your code here
arrayA = np.random.randint(1, 10, (3, 3))
arrayB = np.random.randint(1, 10, (3, 3))

print("3x3 Array:")
print(arrayA)
print(arrayB)

3x3 Array:
[[4 1 4]
 [9 3 1]
 [1 3 3]]
[[9 3 5]
 [2 1 7]
 [2 3 5]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [5]:
# Your code here
summ = arrayA + arrayB
print("Tổng từng phần tử:")
print(summ)

Tổng từng phần tử:
[[13  4  9]
 [11  4  8]
 [ 3  6  8]]


In [7]:
multi = arrayA * arrayB
print("Tích từng phần tử:")
print(multi)

Tích từng phần tử:
[[36  3 20]
 [18  3  7]
 [ 2  9 15]]


In [9]:
# matmul = arrayA @ arrayB
matmul = np.dot(arrayA, arrayB)
print("Tích vô hướng:")
print(matmul)

Tích vô hướng:
[[46 25 47]
 [89 33 71]
 [21 15 41]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [10]:
# Your code here
def array_sum(arr):
    return np.sum(arr)

test_array = np.array([[1, 2, 3], [4, 5, 6]])
print(test_array.size)
print("Tổng tất cả các phần tử trong mảng: ", array_sum(test_array))

6
Tổng tất cả các phần tử trong mảng:  21


In [18]:
k = np.ones((2,3),dtype= np.int16)
l = np.zeros((2,3), dtype= np.int16)
p = k+l+test_array
print(p)
print(p[1,2])

[[2 3 4]
 [5 6 7]]
7
